apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=         # "admin"
  POSTGRES_PASSWORD: YWRtaW5wYXNz # "adminpass"
  POSTGRES_DB: bXlkYg==           # "mydb"
